//
//  Defines.h
//  ecomap
//
//  Created by Anton Kovernik on 06.02.15.
//  Copyright (c) 2015 SoftServe. All rights reserved.
//

#ifndef ecomap_Defines_h
#define ecomap_Defines_h

#define ADDPROBLEMNAVIGATIONVIEWHEIGHT 37.0
#define ADDPROBLEMLOCATIONHEIGHT 137.0
#define ADDPROBLEMNAMEHEIGHT 72.0
#define ADDPROBLEMTYPEHEIGHT 202.0
#define ADDPROBLEMDESCRIPTIONHEIGHT 170.0
#define ADDPROBLEMSOLUTIONHEIGHT 170.0
#define ADDPROBLEMPHOTOHEIGHT 346.0

//#define ADDPROBLEMNAVIGATIONVIEWHEIGHT 37.0
//#define ADDPROBLEMLOCATIONHEIGHT 137.0
//#define ADDPROBLEMNAMEHEIGHT 568
//#define ADDPROBLEMTYPEHEIGHT 568
//#define ADDPROBLEMDESCRIPTIONHEIGHT 568
//#define ADDPROBLEMSOLUTIONHEIGHT 568
//#define ADDPROBLEMPHOTOHEIGHT 568

#endif
